#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: JekJerk

# Short bio or description (displayed in the header)
description: Tabloid style Jekyll-Now template

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: /images/avatar.png

authors:
  hyde:
    name: Mr Hyde
    display_name: Hyde
#    gravatar: numbers
#    email: hyde@somewhere.com
#    web: http://somewhere.com
#    twitter: mrhyde
#    github: mrhyde
  jekyll:
    name: Dr Jekyll
    display_name: Jekyll
#    gravatar: numbers
#    email: jekyll@somewhere.com
#    web: http://somewhere.com
#    twitter: drjekyll
#    github: drjekyll

#
# Flags below are optional
#

collections_dir: collections

collections:
- news
- gossip
- opinion
- sport

collections:
  news:
    output: true
    header: Read all about it
    frontpageposition: 1
  gossip:
    output: true
    header: He said she said
    frontpageposition: 2
  opinion:
    output: true
    header: What we reckon
    frontpageposition: 3
  sport:
    output: true
    header: Winners and losers
    frontpageposition: 4

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email: 
  facebook: 
  flickr:
  github: 
  instagram: 
  linkedin: 
  pinterest:
  rss: # leave blank for none, put anything here to enable
  twitter: 
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/


# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus:

# Enter your Google Analytics web tracking code (e.g. UA-12345678-9) to activate tracking
# google_analytics: #UA-12345678-9

# Your website URL (e.g. http://whatever.github.io or http://www.whatever.com)
# Used for Sitemap.xml and your RSS feed
url: http://whatever.com

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

#
# !! You don't necessarily need to change any of the configuration flags below !!
#

permalink: /:title/

# The release of Jekyll Now that this template was based on (I don't think this does anything?)
version: v1.2.0

# The release of jekjerk that you're looking at here (assuming I remember to update it)
jjversion: 0.1

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  - vendor/ # you might need to change this if you're not developing directly on github
